# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
  - pipeline: '854ed55a-4188-466d-9beb-97635eb75f1c'
    project: 'AzureTestProject'
    source: 'Build pipeline'
    branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'        
    pool:
      vmImage: windows-latest
    
    jobs:    
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Production.DAVE'
      strategy:
       runOnce:
         deploy:           
          steps:
          - checkout: none
          
          - download: ${{ resources.pipelines.pipeline }}
            name: 'DownloadBuildArtifacts'
            displayName: 'Download build artifacts'
            artifact: 'AzureTestProject'
                    
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StopIIS'
            displayName: 'Stop IIS website - ${{ variables.IISWebsiteName }}'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'          
                          
          - task: IISWebAppDeploymentOnMachineGroup@0
            name: 'DeployIIS'
            displayName: 'Deploy IIS website - ${{ variables.IISWebsiteName }}'          
            inputs:
              WebSiteName: '${{ variables.IISWebsiteName }}'              
              Package: '$(Pipeline.Workspace)\${{ resources.pipelines.pipeline }}\AzureTestProject\RoundTheCode.AzureTestProject'
              TakeAppOfflineFlag: true
          
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StartIIS'
            displayName: 'Start IIS website - ${{ variables.IISWebsiteName }}'                
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'
          